app = "n8n-ioi"
primary_region = "gdl"

[env]
  N8N_PORT = "5678"
  N8N_HOST = "0.0.0.0"
  DB_TYPE = "postgresdb"
  DB_POSTGRESDB_HOST = "n8n-db.internal"
  DB_POSTGRESDB_PORT = "5432"
  DB_POSTGRESDB_DATABASE = "n8n"
  DB_POSTGRESDB_USER = "n8n"
  DB_POSTGRESDB_PASSWORD = "changeme"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "changeme"
  GENERIC_TIMEZONE = "America/Mexico_City"

[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[experimental]
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]

[resources]
  memory = "1gb"
  cpu    = "shared"